name: field_investigator_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  fl_chart: ^0.65.0
  intl: ^0.18.1
  geolocator: ^11.0.0
  url_launcher: ^6.2.2 # Added for launching URLs
  table_calendar: ^3.0.9
  http: ^1.2.1
  permission_handler: ^11.3.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0 # Added for loading images from URLs
  shared_preferences: ^2.2.2 # Added for storing user data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
